---
- name: Upgrade system packages
  block:
    - name: Check if running in non-interactive mode
      set_fact:
        non_interactive: "{{ (lookup('env', 'PACKER') == '1' or lookup('env', 'UNATTENDED') == '1') | bool }}"

    - name: Upgrade system in non-interactive mode
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
        dpkg_options:
          - "--force-confdef"
          - "--force-confold"
      environment:
        DEBIAN_FRONTEND: noninteractive
        DEBIAN_PRIORITY: critical
      when: non_interactive

    - name: Upgrade system in interactive mode
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: not non_interactive

- name: Check if sudo is installed
  command: which sudo
  register: sudo_check
  ignore_errors: yes

- name: Install etckeeper without sudo
  apt:
    name: etckeeper
    state: present
  when: sudo_check.rc != 0

- name: Install sudo
  apt:
    name: sudo
    state: present
  when: sudo_check.rc != 0

- name: Install curl
  apt:
    name: curl
    state: present
  when: sudo_check.rc != 0

- name: Add user to sudo group
  user:
    name: "{{ misp_user }}"
    groups: sudo
    append: yes
  when: sudo_check.rc != 0

- name: Update package list
  apt:
    update_cache: yes
  when: sudo_check.rc == 0


#########################################################
####add the misp user to staff and www-data (mandatory)
- name: Check if /usr/local/src exists and get its attributes
  stat:
    path: /usr/local/src
  register: src_dir
  ignore_errors: yes

- name: Ensure /usr/local/src directory exists and has correct permissions
  block:
    - name: Create /usr/local/src directory if it doesn't exist
      file:
        path: /usr/local/src
        state: directory
        mode: "2775"
        owner: root
        group: staff
      when: src_dir.stat.exists == false

    - name: Check if /usr/local/src is writable by {{ misp_user }}
      set_fact:
        src_writable_by_user: "{{ src_dir.stat.is_writable and src_dir.stat.uid == lookup('file', '/etc/passwd', splitlines=True | selectattr('startswith', misp_user)).split(':')[2] }}"
      when: src_dir.stat.exists

    - name: Set permissions on /usr/local/src if not writable by {{ misp_user }}
      file:
        path: /usr/local/src
        mode: "2775"
        owner: root
        group: staff
      when: not src_writable_by_user|default(false)

  when: src_dir.stat.exists|default(false) == false or src_dir.stat.is_writable|default(false) == false

